# Revit Batch Processor -- GPL-3.0-or-later.
# Writes the winget manifest (version, defaultLocale and installer files, schema 1.12.0)
# of a Britton release, for a private winget source. See docs/winget.md.
#
# The installer hash comes from -InstallerPath (the file built by the release workflow)
# or, when omitted, from the installer downloaded from the GitHub release of the tag.
# Output: <OutputDir>/Britton.RevitBatchProcessor/<X.Y.Z.N>/*.yaml, the folder layout
# expected by `winget validate --manifest` and Add-WinGetManifest.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Tag,
    [string]$InstallerPath,
    [string]$OutputDir = 'winget-manifests',
    [string]$Repository = 'omanningham/RevitBatchProcessor'
)
$ErrorActionPreference = 'Stop'

# Same tag rule as set_version.ps1: winget only receives Britton releases.
if ($Tag -cnotmatch '^v(\d+\.\d+\.\d+)-brt\.([1-9]\d{0,4})$' -or [int]$Matches[2] -gt 65535) {
    throw "Unexpected Britton release tag (expected vX.Y.Z-brt.N): $Tag"
}
$version = "$($Matches[1]).$($Matches[2])"
$displayVersion = $Tag.Substring(1)

$packageId = 'Britton.RevitBatchProcessor'
$packageName = 'Revit Batch Processor (Britton)'
$publisher = 'Britton'
# Inno Setup registers the uninstall key "<AppId>_is1"; AppId is shared with upstream.
$productCode = '{B5CA57EA-7BB2-4620-916C-AE98376C1EF1}_is1'
$repoUrl = "https://github.com/$Repository"
$installerUrl = "$repoUrl/releases/download/$Tag/RevitBatchProcessorSetup_$Tag.exe"
$manifestVersion = '1.12.0'
$schemaBase = "https://aka.ms/winget-manifest"

if (-not $InstallerPath) {
    $InstallerPath = Join-Path ([IO.Path]::GetTempPath()) "RevitBatchProcessorSetup_$Tag.exe"
    Write-Host "Downloading $installerUrl"
    Invoke-WebRequest -Uri $installerUrl -OutFile $InstallerPath -UseBasicParsing
}
$sha256 = (Get-FileHash -Path $InstallerPath -Algorithm SHA256).Hash

$header = "# Generated by .github/scripts/new_winget_manifest.ps1 from tag $Tag."
$files = @{
    "$packageId.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.version.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
DefaultLocale: fr-CA
ManifestType: version
ManifestVersion: $manifestVersion
"@
    "$packageId.locale.fr-CA.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.defaultLocale.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
PackageLocale: fr-CA
Publisher: $publisher
PackageName: $packageName
PackageUrl: $repoUrl
License: GPL-3.0-or-later
LicenseUrl: $repoUrl/blob/master/LICENSE.txt
ShortDescription: Traitement par lots de fichiers Revit avec des scripts Python ou Dynamo (version Britton $displayVersion).
Description: |-
  Version Britton de Revit Batch Processor : addins Revit 2015 à 2027 et interface BatchRvtGUI.
  Fermer Revit avant l'installation ou la mise à jour : les addins sont remplacés dans le profil Windows.
Moniker: revit-batch-processor
Tags:
- revit
- autodesk
- batch
- python
- dynamo
ReleaseNotesUrl: $repoUrl/releases/tag/$Tag
ManifestType: defaultLocale
ManifestVersion: $manifestVersion
"@
    "$packageId.installer.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.installer.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '$productCode'
AppsAndFeaturesEntries:
- DisplayName: $packageName $displayVersion
  Publisher: $publisher
  DisplayVersion: $version
  ProductCode: '$productCode'
Installers:
- Architecture: x64
  InstallerUrl: $installerUrl
  InstallerSha256: $sha256
ManifestType: installer
ManifestVersion: $manifestVersion
"@
}

$dir = Join-Path $OutputDir (Join-Path $packageId $version)
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
foreach ($name in $files.Keys) {
    [IO.File]::WriteAllText((Join-Path $dir $name), $files[$name].Replace("`r`n", "`n") + "`n", $utf8NoBom)
}
Write-Host "Manifest $packageId $version written to $dir (SHA256 $sha256)"
# Forward slashes: the release upload step uses the folder in a glob, where "\" escapes.
if ($env:GITHUB_OUTPUT) { "manifest_dir=$($dir -replace '\\', '/')" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8 }
