# Revit Batch Processor -- GPL-3.0-or-later.
# Writes the winget manifest (version, defaultLocale and installer files) of a Britton
# release, for a private winget source. See docs/winget.md. Schema 1.10.0: the latest
# version accepted by the Microsoft.WinGet.RestSource server.
#
# Versions come from the tag and the installer identity (ProductCode, names, publisher)
# from the Inno script, through release_metadata.ps1, so the manifest matches what the
# installer registers. The installer hash comes from -InstallerPath (release workflow)
# or, for a manual run, from the digest GitHub publishes for the release asset, with a
# download of the installer as fallback.
# Output: <OutputDir>/Britton.RevitBatchProcessor/<X.Y.Z.N>/*.yaml, the folder layout
# expected by `winget validate --manifest` and Add-WinGetManifest.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Tag,
    [string]$InstallerPath,
    [string]$OutputDir = 'winget-manifests',
    [string]$Repository,
    [string]$IssPath
)
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'release_metadata.ps1')

# GITHUB_REPOSITORY is set in workflows; the fork is the default for a manual run.
if (-not $Repository) { $Repository = if ($env:GITHUB_REPOSITORY) { $env:GITHUB_REPOSITORY } else { 'omanningham/RevitBatchProcessor' } }
if (-not $IssPath) { $IssPath = Join-Path (Split-Path (Split-Path $PSScriptRoot)) 'Setup/RevitBatchProcessor.iss' }

$release = ConvertFrom-ReleaseTag -Tag $Tag -BrittonOnly
$installer = Get-InstallerIdentity -IssPath $IssPath -Release $release
$version = $release.Version

$packageId = 'Britton.RevitBatchProcessor'
$repoUrl = "https://github.com/$Repository"
$installerName = "RevitBatchProcessorSetup_$Tag.exe"
$installerUrl = "$repoUrl/releases/download/$Tag/$installerName"
$manifestVersion = '1.10.0'
$schemaBase = 'https://aka.ms/winget-manifest'

if ($InstallerPath) {
    $sha256 = (Get-FileHash -Path $InstallerPath -Algorithm SHA256).Hash
} else {
    $releaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repository/releases/tags/$Tag" -Headers @{ 'User-Agent' = 'new_winget_manifest.ps1' }
    $asset = @($releaseInfo.assets | Where-Object { $_.name -eq $installerName })
    if ($asset.Count -ne 1) { throw "Installer $installerName not found in release $Tag of $Repository" }
    $sha256 = ConvertFrom-AssetDigest $asset[0].digest
    if (-not $sha256) {
        # No digest for this asset: hash a downloaded copy, then delete it.
        $download = Join-Path ([IO.Path]::GetTempPath()) ([IO.Path]::GetRandomFileName())
        try {
            # The progress bar slows large downloads under Windows PowerShell 5.1.
            $ProgressPreference = 'SilentlyContinue'
            Write-Host "Downloading $installerUrl"
            Invoke-WebRequest -Uri $installerUrl -OutFile $download -UseBasicParsing
            $sha256 = (Get-FileHash -Path $download -Algorithm SHA256).Hash
        } finally {
            Remove-Item -LiteralPath $download -ErrorAction SilentlyContinue
        }
    }
}

$header = "# Generated by .github/scripts/new_winget_manifest.ps1 from tag $Tag."
$files = @{
    "$packageId.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.version.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
DefaultLocale: fr-CA
ManifestType: version
ManifestVersion: $manifestVersion
"@
    "$packageId.locale.fr-CA.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.defaultLocale.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
PackageLocale: fr-CA
Publisher: $($installer.Publisher)
PackageName: $($installer.PackageName)
PackageUrl: $repoUrl
License: GPL-3.0-or-later
LicenseUrl: $repoUrl/blob/master/LICENSE.txt
ShortDescription: Traitement par lots de fichiers Revit avec des scripts Python ou Dynamo (version Britton $($release.DisplayVersion)).
Description: |-
  Version Britton de Revit Batch Processor : addins Revit 2015 à 2027 et interface BatchRvtGUI.
  Fermer Revit avant l'installation ou la mise à jour : les addins sont remplacés dans le profil Windows.
Moniker: revit-batch-processor
Tags:
- revit
- autodesk
- batch
- python
- dynamo
ReleaseNotesUrl: $repoUrl/releases/tag/$Tag
ManifestType: defaultLocale
ManifestVersion: $manifestVersion
"@
    "$packageId.installer.yaml" = @"
$header
# yaml-language-server: `$schema=$schemaBase.installer.$manifestVersion.schema.json

PackageIdentifier: $packageId
PackageVersion: $version
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '$($installer.ProductCode)'
AppsAndFeaturesEntries:
- DisplayName: $($installer.DisplayName)
  Publisher: $($installer.Publisher)
  DisplayVersion: $version
  ProductCode: '$($installer.ProductCode)'
Installers:
- Architecture: x64
  InstallerUrl: $installerUrl
  InstallerSha256: $sha256
ManifestType: installer
ManifestVersion: $manifestVersion
"@
}

$dir = Join-Path $OutputDir (Join-Path $packageId $version)
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
foreach ($name in $files.Keys) {
    [IO.File]::WriteAllText((Join-Path $dir $name), $files[$name].Replace("`r`n", "`n") + "`n", $utf8NoBom)
}
Write-Host "Manifest $packageId $version written to $dir (SHA256 $sha256)"
# Forward slashes: the release upload step uses the folder in a glob, where "\" escapes.
if ($env:GITHUB_OUTPUT) { "manifest_dir=$($dir -replace '\\', '/')" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8 }
